Gemfile, Gemfile.lock, config/unicorn.rb
・What
デプロイ関連の環境構築
->config/unicorn.rbの編集
->gem 'unicorn', '5.4.1'をGemfileに追加（本番環境用のみ）
・Why
->デプロイに必要
=> [WIP]デプロイ環境構築

config/database.yml
・what
本番環境用のDBを作成する
・why
デプロイの動作確認で必要なため
=> [wip]本番環境db作成

config/unicorn.rb
・what
elasticIPでアクセスできるようにunicorn.rbのポート指定箇所を変更
・why
本番環境でelasticIPでアクセスできるようにするため
=> [WIP]本番環境用にunicornのポートを変更

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/environments/production.rb, config/unicorn.rb
・what
capostranoの導入(gem、unicorn.rbなどの編集）
・why
capostranoによる自動デプロイをするため
=> [wip]capostranoの導入

config/environments/production.rb
・what
マスターキーをgitに登録する
・why
apiのキーを登録する時にみんなが操作できるようにするため
=> [WIP]master_keyをgitに登録

README.md
READMEへDB設計を記載
アプリ設計に必要なテーブルとリレーションを識別するため
=> write DB design to README

config/deploy.rb
・what
basic認証の追記
・why
本番環境でbasic認証を有効にするため
=> [WIP]basic認証追記

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/mypage_logout.scss, app/controllers/items_controller.rb, app/views/items/logout.html.haml, config/routes.rb
マイページのログアウト画面のビューファイルの作成
#why
ユーザーが老グアウト出来るページ作成のため
=> render side-bar,create logout

app/assets/stylesheets/application.scss, config/routes.rb
・what
routes.rb
application.scssのシンタックスエラーを直した
・why
デプロイでエラーした
=> [WIP]リファクタリング

app/assets/stylesheets/modules/mypage_identification.scss, app/views/items/show.html.haml
=> addパンくず,コードレビュー

app/assets/stylesheets/modules/create_sell-btn.scss, app/assets/stylesheets/modules/user_profile.scss, app/views/items/new.html.haml, app/views/modules/_sell-btn.html.haml, app/views/users/create.html.haml, app/views/users/destroy.html.haml, app/views/users/identification.html.haml, app/views/users/logout.html.haml, app/views/users/new.html.haml, app/views/users/show.html.haml, config/routes.rb
商品出品のボタン用の部分テンプレート作成（ページの右下にあるやつ）
本家にあるページにはつけてます。（マイページトップ,カード新規追加削除,マイページログアウト,マイページ本人情報）
=> add sell-btn to require pages

app/assets/stylesheets/modules/mypage_identification.scss, app/assets/stylesheets/modules/mypage_logout.scss, app/views/users/identification.html.haml, app/views/users/logout.html.haml
=> add header

README.md, app/models/item.rb, db/migrate/20190830235905_create_items.rb, db/schema.rb, test/fixtures/items.yml, test/models/item_test.rb
itemモデルとitemテーブルの追加,itam-nameにindex追加
=> itemモデルとitemテーブルの追加,itam-nameにindex追加

app/controllers/jp/users_controller.rb, app/controllers/users/registrations_controller.rb, config/routes.rb
What
ユーザ会員登録関連のルーティングを変更
Why
これからサーバサイド側の実装に入るため
=> [WIP]ユーザ会員登録関係のルーティング変更

app/assets/stylesheets/modules/item_sell.scss, app/controllers/jp/items_controller.rb, app/models/item_image.rb, app/views/jp/items/_image.html.haml, app/views/jp/items/new.html.haml, config/routes.rb
#what
add new action item controller,change route sell→new
=> add new action item controller,change route sell→new

app/assets/stylesheets/modules/item_details.scss, app/assets/stylesheets/modules/toppage.scss, app/views/items/index.html.haml, app/views/items/show.html.haml
=> 商品詳細ページcss修正

app/assets/javascripts/category.js, app/controllers/items_controller.rb, app/models/item.rb, app/uploaders/image_uploader.rb, app/views/items/edit.html.haml, app/views/items/new.html.haml
#what 
uploaderのサイズを修正
商品編集ページのカテゴリーが親しか表示されていなかったので、サイズまで表示されるように修正
商品モデルにバリデーションを追加
=> fixed edit-category,image-size add validattions

app/assets/javascripts/check_forbidden_word.js, app/assets/javascripts/user_create.js, app/assets/stylesheets/modules/create_user.scss, app/controllers/users/registrations_controller.rb, app/views/users/registrations/email_check.json.jbuilder, app/views/users/registrations/step1.html.haml, config/routes.rb
WHAT
Implement the function to confirm the uniqueness of the email address with javascript
・Routing construction
・jbuilder construction
・Display error messages dynamically
WHY
To ensure the uniqueness of email addresses
To notify the error instantly
Usability improvements
=> [WIP]Uniqueness-guranteed-with-JS

app/assets/javascripts/user_create.js, app/assets/stylesheets/modules/create_user.scss, app/controllers/users/registrations_controller.rb, app/models/user.rb
WHAT
Server-side validation when registering new users
・create Validation of user model
=>create original validation for phone_number,email,zenkaku-kana-kanji-hiragana
・create Validation of user controller
WHY
To guarantee user registration validation on the server side
=> [WIP]Server-side validation when registering new users

README.md, app/assets/stylesheets/modules/item_sell.scss, app/assets/stylesheets/modules/mypage_logout.scss, app/controllers/items_controller.rb, app/views/items/edit.html.haml, app/views/items/new.html.haml, app/views/users/identification.html.haml
=> Color variableization,Delete unnecessary comments

app/models/sns_credential.rb, spec/controllers/omniauth_callback_controller_spec.rb, spec/factories/sns_credential.rb, spec/models/sns_credential_spec.rb, spec/rails_helper.rb, spec/support/omniauth_macros.rb
WHAT
・sns_credentials unit test
->sns_credentials unit test with rspec
WHY
・To expect data for the application to function properly.
=> [WIP]sns_credentials unit test

app/controllers/users/registrations_controller.rb, app/models/address.rb, spec/factories/address.rb, spec/factories/user.rb, spec/models/address_spec.rb
WHAT
・Address model unit test
->Address model unit test with rspec
WHY
・To expect data for the application to function properly.
=> [WIP]Address table unit test

app/assets/javascripts/category.js, app/controllers/items_controller.rb, app/views/items/edit.html.haml
カテゴリーを初期値にした時に、生成されたセレクトボックスをremoveするようにしました。
=> set category remove

app/controllers/items_controller.rb
=> fixed_images_trable
